out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: generic_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: graph
  layer_type: egdfg
  layers_pre_mp: 0
  layers_mp: 4
  dim_inner: 64
  batchnorm: True
  norm_type: batchnorm
  act: relu
  dropout: 0.15
  agg: mean
  normalize_adj: False
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 5e-5
  base_lr: 0.001
  max_epoch: 2000
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 15
  min_lr: 1e-6
